### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by Craneberry**

### CODE REVIEW

**Comment by Rafiot** [comment]
I cannot merge the PR as it is, as it changes (almost) everything and is very difficult to properly see what it is supposed to do.

For example, I see you add a clamav support. It might make sense to implement it as an optional functionality.

**Comment by Craneberry** [comment]
Yes of course, I am aware of that. This pull was more for changes on file._checkfilename(), Config.timeout, GroomerLogger.add_file() (size formatting), ...
I will work further on clamav integration.
I've also started a wiki, if you want to take a look.

(sorry first time on git)

**Comment by dputtick** [comment]
@Craneberry 
Thanks for your suggestions! Some things I like from this PR:

* Having a whitelist for characters in filenames. Should we apply this to full paths? What do we do about characters from other alphabets - let's say a user wants to use Circlean in China?
* We've been talking about automating setup, but I'm not sure a shell script is a great idea, something like make would be better. If we're going to do it, it would be nice to make it a little more modular, like having different commands in the makefile.
* A timeout for unpacking archives. Would be a good idea to think about how long this should be by default, and how we would handle the condition when the timeout is hit. Do we make the file dangerous automatically?
* Adding filesize units to the logger.

Questions I have:
* What is your threat model for changing the permissions of text files to read only when copied? If a text file is actually a script, its mimetype will be identified as such, and it will be marked dangerous. Maybe we want to change all dangerous files to being not-executable? That might be worth considering. @Rafiot thoughts?
* Why do you feel that it's better to have the FileBase code located in a separate file? For me, filecheck.py still makes sense as one script: all of the functionality is closely related and there are no other components involved. If the file was over ~1000 lines and the classes had more independent functionality, I would personally be more convinced.


Also, if you'd like to have more discussion of proposed changes (like the clamav thing) before you implement them, definitely open an issue! That way we can discuss the implementation beforehand :)

**Comment by Craneberry** [comment]
Hello,
Thank you for your feedback! I didn't know about opening an issue. 
The goal for me is to implement a .conf file to make it easy for people or organisations to implement their own security policy. So, to answer the questions :
1) Maybe the language could be set in this conf file (just copy/paste caracter some a specific language). 
2) I agree. I just put this file because it took me too much time to install all the libraries. It's easier to put other dependencies if needed during dev.
3) I think an archive should not be bigger than 2 or 3GB unpacked (. It could be interesting to check the size before unpacking too.
4) 
5) Linux doesn't need an extension to execute a script and I didn't check what libmagic returns for each script language. I think it's also very easy to write "./" in front of a file, even if you don't want to. For this reasons maybe it's better to change rights (something to add in the conf file too).
6) During the first readings, the file seemed very long and difficult to understand for me. The idea was to gather the classes Config and File in a file, which are the most important classes in file treatment. It then should be easier for a user to configure his own security policy. 
Let me know about this idea of parsing a conf file, to add functionalities to the code.

**Comment by dputtick** [comment]
@Craneberry 
Hmm, those are interesting ideas.

1. In terms of having a configuration file, I think that's sort of what we have already with the Config object. This could easily be abstracted into a file type + a parser. The problem is, the more complex logic is hard to express in a configuration. Once the configuration is complex enough, it probably makes more sense to just write custom code. Do you have an idea what you would like a configuration file to look like? It feels to me like a better option for customizing a security policy involves building a new script on top of the pycirclean API.
2. Ok, got it. Make we should keep your file out of the main repository then. I think opening an issue for writing a proper makefile would make sense.
3. Why 2 or 3 GB? Keep in mind that filecheck.py is specifically for sanitizing USB keys. I think it would be reasonable to expect something that was more than 4GB compressed on a USB key. I'm also having a hard time thinking about a timeout because I don't have a good intuition for how long unpacking an archive should take on a Raspberry Pi.
5. We should open an issue to discuss changing the permissions on copied files that are dangerous. I think it's potentially a good idea.
6. I see. I think that one path forward for making it easier to understand the code would be improving the documentation. This has been a thing that I have half-finished notes for which I need to add. I saw you started writing documentation on your wiki, I think that it's a good idea.

**Comment by Craneberry** [comment]
@dputtick 
 I did a commit where there's a conf file example, parsed with configparser in Config class. It works fine but doesn't handle errors yet. It might be easier for the common user than looking into the code.

**Comment by Rafiot** [comment]
A few points regarding the logic behind the way PyCIRCLean is implemented now.

The library aims to propose an easy interface for the end user and hide the complexity as much as possible, when the person implementing the solution needs to have good python knowledges.

1. ConfigParser vs. Python file: in our case, the configuration is relatively complex and a flat config file is prone to typos: `Make sure ", " is present as separator ` will be more difficult to debug in case the implementer makes a mistake and give very weird errors to the enduser. Using a python file will just fail having a typo will just die the fisrt time the implementer tests it. I wouldn't mind having the Config in an external file for example, but the python file option will be more reliable.
2. Having an install script makes sense, especially if we can get to a point where it does everything (download the image, installs all the dependencies, and set everything up).
3. Checking the expected size of the archive after extraction makes sense, I'll open an issue for that.
4. The executable bit is only applicable on linux FS, it is in fact a good idea, but the code needs to make sure it won't fail if the project runs on FAT/NTFS/....
5. Agree, we need more documentation to allow the implementation of your own security policy, but again, I strongly recommend python file and not flat text config file for debug purposes.

**Pull request closed without merging**
